### ISSUE TITLE
tcp.client and tcp.client.persistent attempt TLS/SSL connection when disabled

### ISSUE THREAD

**Issue by K-McNicoll** [amx-itg/muse-driver-amx-ipcomm#1]
When the Driver ID is set to ipcomm.tcp.client or ipcomm.tcp.client.persistent and TLS enable is not checked, the device still sends out a TLS Client Hello packet as if it is trying to connect via TLS. Device instance remains in the offline state

**Comment by ircraigie** [comment]
> When the Driver ID is set to ipcomm.tcp.client or ipcomm.tcp.client.persistent and TLS enable is not checked, the device still sends out a TLS Client Hello packet as if it is trying to connect via TLS. Device instance remains in the offline state

There is a sslsocket.connect() test to see if TLS is required at the server but not enabled at the Driver configuration before the connection is "officially" established through the nio library.

**Comment by K-McNicoll** [comment]
Is it possible to disable that test as some devices that don't support TLS don't like receiving a bunch of "random" data?

What influences the offline / online state of a TCP client? The state indicator remains offline even when the server on theother end indicates it is connected to a client (The same client that sent the TLS data).

**Comment by ircraigie** [comment]
> Is it possible to disable that test as some devices that don't support TLS don't like receiving a bunch of "random" data?
> 
> What influences the offline / online state of a TCP client? The state indicator remains offline even when the server on theother end indicates it is connected to a client (The same client that sent the TLS data).

I'll look at disabling the test but the underlying nio engine (I don't have access to SDK source code) did some really bad things when a TCP connection was attempted to a TLS required server - and vice versa.  

The offline/online state depends on which variant you are using.  The driver handles that for you for the "persistent" variants otherwise you are responsible for setting the parameter state from a script - check the github README or the at the Muse controller CLI (doc:list / doc:show <docId>) for the Command: deviceonline documentation.

**Comment by K-McNicoll** [comment]
I noticed 2 things when the TLS Client Hello is sent:
1. The program on the device (I am running python) locks up completely
2. The device state remains offline (using the persistent version of the driver)
If I force the connection closed from the server, this driver will reopen it without sending the TLS client hello and normal functionality is restored, but it definitely seems like that TLS check is also doing bad things when the server doesn't support it

**Comment by ircraigie** [comment]
> I noticed 2 things when the TLS Client Hello is sent:
> 
> 1. The program on the device (I am running python) locks up completely
> 2. The device state remains offline (using the persistent version of the driver)
>    If I force the connection closed from the server, this driver will reopen it without sending the TLS client hello and normal functionality is restored, but it definitely seems like that TLS check is also doing bad things when the server doesn't support it

AMX-IPComm-1.0.3 has a change to the test where the TLS Client Hello should only be sent out when the TLS configuration property is TRUE.

**Comment by K-McNicoll** [comment]
Issue is resolved
