### ISSUE TITLE
amx-ipcomm driver fault event (.fault argument vs .exception)

### ISSUE THREAD

**Issue by DavidVine** [amx-itg/muse-driver-amx-ipcomm#2]
The readme for the AMX-IPComm extension (shown on this GitHub page and in via the MUSE CLI via the doc:show amx-ipcomm command) refers to the ```fault``` argument in the object passed to the ```fault``` event, e.g:

```
var svsiEnc = context.devices.get("tcpclient");

svsiEnc.fault.listen(function(event) {
context.log.info(String(event.arguments.fault));
});
```

However, the ```fault``` property does not actually exist on the ```arguments``` object within the object passed to the ```fault``` event. It is actually ```exception``` (e.g., ```event.arguments.exception``` in JavaScript/Groovy or ```event.arguments['exception']``` in Python). I checked v1.0.0, v1.0.2, and v1.0.3 of the amx-ipcomm extension and they all have the ```exception``` property, not the ```fault``` property.

Personally I think it should be ```event.arguments.fault```, not ```event.arguments.exception```, as this would be consistent with other devices' ```fault``` events like the serial and IR ports of the idevice device. Either way, we need the documentation and any example code provided by HARMAN to match the actual identifiers of the event object arguments.

**Comment by ircraigie** [comment]
Nw publishing at the fault event with arguments "fault" (error/exception message ) and "exception" (exception class is thrown) (v1.0.4)

README to be update with publishing of v1.0.4

**Comment by DavidVine** [comment]
Thanks Ian. Closing.
