### ISSUE TITLE
Issues with Multiple Versions of the AMX-IPComm Extension Uploaded to a MUSE Controller

### ISSUE THREAD

**Issue by DavidVine** [amx-itg/muse-driver-amx-ipcomm#5]
I have observed that if you have installed multiple versions of the amx-ipcomm MUSE Extension on a MUSE controller it's almost impossible to get the version running that you want to run.

Short of a factory reset there's no obvious way to delete an extension from a MUSE controller. Even if you uninstall it you can't remove it so if you upload another version of the extension to the controller you can see that there are multiple versions loaded but even if you select the version you want to run and press the Install button it doesn't necessarily mean that version will be the one that runs.

The only way I can tell which version of the amx-ipcomm extension is actually running from it's behaviour when connecting to a TCP server. If it send a TLS client hello when establishing a connection to a TCP server it's ```v1.0.2```, if it connects but then immediately disconnects, and then immediately reconnects again it's ```v1.0.3```, and if it connects with no issues but doesn't trigger the ```fault``` event when there is a connection issue (and only has a TCP and UDP driver available) then it's ```v1.0.0```.

I realise this might be an issue on the MUSE controller itself so have also reported this to HARMAN APAC Tech Support but am posting here as well in case there's anything on the extension side that might be causing this behaviour.

**Comment by ircraigie** [comment]
Not a Driver issue.

**Comment by DavidVine** [comment]
Thanks Ian. Have pushed that one to HARMAN APAC TS.
